#!/usr/bin/env bash

cd laradock &&
docker-compose exec --user=laradock workspace mysql -uroot -e 'CREATE DATABASE mvm_testing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
docker-compose exec --user=laradock workspace php artisan migrate
cd ..
