#!/usr/bin/env bash

cd laradock &&
echo 'Linting app'
docker-compose exec --user=laradock workspace ./vendor/tightenco/tlint/bin/tlint lint app --ansi
echo 'Linting domain'
docker-compose exec --user=laradock workspace ./vendor/tightenco/tlint/bin/tlint lint domain --ansi
echo 'Linting support'
docker-compose exec --user=laradock workspace ./vendor/tightenco/tlint/bin/tlint lint support --ansi
cd ..
