#!/usr/bin/env bash

cd laradock &&
echo 'Create database'
docker-compose exec --user=root mysql mysql -uroot -proot --silent --execute 'CREATE DATABASE mvm_testing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
echo 'Migrate tables'
docker-compose exec --user=laradock workspace php artisan migrate
cd ..
